.dashWebrtc_js_metadata <- function() {
deps_metadata <- list(`dash_webrtc` = structure(list(name = "dash_webrtc",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashWebrtc.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebrtc",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_webrtc` = structure(list(name = "dash_webrtc",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashWebrtc.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebrtc",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_webrtc` = structure(list(name = "dash_webrtc",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_webrtc.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebrtc",
all_files = FALSE), class = "html_dependency"),
`dash_webrtc` = structure(list(name = "dash_webrtc",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_webrtc.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashWebrtc",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
